version: "2"
services:
  app:
    build: ./app
    #links:
    #  - db
    network_mode: "host"
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    network_mode: "host"
    volumes:
      - ./db:/var/lib/mysql
