version: "2"
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking
    volumes:
      - /dev/shm/db_res:/var/lib/mysql
  app:
    depends_on:
      - db
    build: ./app
    network_mode: "host"
    ports:
      - "5002:5002"
