version: '3'
services:
  app:
    container_name: docker_node_mongo
    build: .
    ports: 
      - '3000:3000'
    links:
      - mongo
  mongo: 
    container_name: mongo
    image: mongo
    volumes:
      - /dev/shm/db_review:/data/db
    expose:
      - '27017'
    
